FROM nginx

ENV PORT=80

# Set user to root
USER root

# Copy files
COPY "./" /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
RUN chmod -R 755 /usr/share/nginx/html

# Replace the port in the nginx config file

# Run Nginx in the foreground
CMD sed -i "s/port/$PORT/g" /etc/nginx/nginx.conf && nginx -g 'daemon off;'
