FROM nginx

# set user to root
USER root

# copy files
COPY "./" /usr/share/nginx/html
COPY default.conf.template /etc/nginx/conf.d/default.conf.template
RUN chmod -R 755 /usr/share/nginx/html

# update port
CMD /bin/sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'
