services:
  backend:
    build:
      context: ./backend
    image: zenithatic/bookshelfai-backend:latest
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    image: zenithatic/bookshelfai-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
